FROM golang:1.26.6-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates && \
    go install github.com/air-verse/air@v1.67.3

COPY go.mod go.sum ./
RUN go mod download

ARG VERSION=dev
ARG COMMIT=unknown
ARG BUILD_TIME=unknown

ENV APP_VERSION=${VERSION}
ENV APP_COMMIT=${COMMIT}
ENV APP_BUILD_TIME=${BUILD_TIME}

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
